/**
 * LY.com Inc.
 * Copyright (c) 2004-2016 All Rights Reserved.
 */
package com.ly.ta.form;

import com.ly.ta.annotation.InputType;
import com.ly.ta.annotation.TaCrud;
import com.ly.ta.annotation.TaCrudInfo;

/**
 * TaAdminUserDO
 * database table: ta_admin_user
 * database table comments: TaAdminUser
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
@TaCrud(pageTitle = "用户管理", commandName = "userForm", viewName = "User")
public class TaAdminUserDO implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/**
	 * id 		db_column: id 
	 */
	private long id;
	/**
	 * password 		db_column: password 
	 */
	@TaCrudInfo(order = 1, label = "登录密码", path= "password")
	private String password;
	/**
	 * loginName 		db_column: login_name 
	 */
	@TaCrudInfo(order = 0, label = "登录名", path= "loginName", desc = "限15字")
	private String loginName;
	/**
	 * email 		db_column: email 
	 */
	@TaCrudInfo(order = 2, label = "邮箱", path= "email", desc = "限50个字符内")
	private String email;

	@TaCrudInfo(order = 3, label = "适应范围", path= "scope", inputType = InputType.RADIO)
	private String scope;
}

